### ISSUE TITLE
problem running ./configure inside flashcc's cygwin environment and $PATH with problems

### ISSUE THREAD

**Issue by fungos** [alexmac/alcextra#1]
Trying to run the make or ./configure directly give plenty of these errors.

Example trying to run libpng configure:

./configure: line 18: $'\r': command not found
./configure: line 33: syntax error near unexpected token `newline'
'/configure: line 33:`     ;;

Also, the Makefile makes reference to $PATH from environment (windows ones) but if there are some paths like "Program Files (x86)"  that will brack in the `(' char.

**Comment by fungos** [comment]
Had to put " in the $(PATH) on Makefile:

ENV=PATH=$(FLASCC)/usr/bin:$(INSTALL)/usr/bin:"$(PATH)" PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) CC=gcc CXX=g++ CFLAGS=-O4 CXXFLAGS=-O4

The \r problem is due to checkout with git console and not cygwin console.

**Comment by liubo-bj** [comment]
dos2unix configure
